/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "../frontend/index.html",
    "../frontend/src/**/*.js",
  ],
  safelist: [
    // Colores de estado dinámicos
    'bg-yellow-500',
    'bg-orange-500',
    'bg-red-600',
    'bg-purple-600',
    'bg-teal-600',
    'bg-amber-500',
    'bg-gray-400',
    // Clases del modal "Ver Reserva" que no se detectan
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'gap-6',
    'space-y-4',
    'font-semibold',
    'text-gray-800',
    'border-b',
    'pb-1',
    'mb-2',
    'text-sm',
    'gap-x-4',
    'gap-y-1',
    'text-gray-500',
    'col-span-2',
    'text-xs',
    'bg-gray-50',
    'p-2',
    'rounded',
    'whitespace-pre-wrap',
    'border-t',
    'pt-4',
    'mt-4',
    'text-green-600',
    'text-red-600',
    'font-bold',
    'max-h-40',
    'overflow-y-auto',
    'text-right',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}