/**
 * @fileoverview Centralized Firestore Models for SuiteManager IA
 * Defines the schema and helper functions for interacting with Firestore.
 * Supports both SSR (Admin) and Concierge (Chat) modules.
 */

const { Timestamp } = require('firebase-admin/firestore');

/**
 * Collection Names Enum
 */
const COLLECTIONS = {
    EMPRESAS: 'empresas',
    PROPIEDADES: 'propiedades',
    PHOTOS: 'photos' // Global or subcollection depending on usage
};

/**
 * @typedef {Object} SiteConfig
 * @property {string} domain - e.g., "myhotel.suitemanagers.com"
 * @property {string} primaryColor - Hex code
 * @property {string} secondaryColor - Hex code
 * @property {object} seo - Global SEO settings
 */

/**
 * @typedef {Object} Empresa
 * @property {string} nombre
 * @property {string} plan - 'free', 'pro', 'premium'
 * @property {SiteConfig} siteConfig
 * @property {Timestamp} createdAt
 * @property {Timestamp} updatedAt
 */

/**
 * @typedef {Object} Propiedad
 * @property {string} empresaId - Parent reference
 * @property {object} infoBase - Core data (capacity, location)
 * @property {object} websiteData - SSR specific data (slug, texts)
 * @property {Array<Componente>} componentes - List of rooms/spaces
 * @property {Array<Photo>} images - Optimized image list
 */

/**
 * Helper to structure a new Empresa document
 * @param {string} nombre 
 * @param {string} plan 
 * @returns {Empresa}
 */
const createEmpresaModel = (nombre, plan = 'free') => ({
    nombre,
    plan,
    siteConfig: {
        domain: '',
        primaryColor: '#4F46E5', // Default Indigo
        secondaryColor: '#10B981', // Default Green
        seo: {
            homeTitle: '',
            homeDescription: ''
        }
    },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now()
});

/**
 * Helper to structure a new Propiedad document
 * @param {string} empresaId 
 * @param {object} baseData 
 * @returns {Propiedad}
 */
const createPropiedadModel = (empresaId, baseData) => ({
    empresaId,
    infoBase: {
        nombre: baseData.nombre || '',
        capacidad: baseData.capacidad || 2,
        ubicacion: baseData.ubicacion || {}, // { lat, lng, address }
        tipo: baseData.tipo || 'Cabaña'
    },
    websiteData: {
        slug: '', // To be generated
        aiDescription: '', // Generated by AI
        features: [] // ['Wifi', 'Parking']
    },
    componentes: [], // [{ id, tipo, nombre, fotosRequeridas }]
    images: [], // [{ id, url, tags, category }]
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now()
});

module.exports = {
    COLLECTIONS,
    createEmpresaModel,
    createPropiedadModel
};
